### ISSUE TITLE
Sicherheitsabfrage bei Zurücksetzen

### ISSUE THREAD

**Issue by JonasDeichelmann** [sancardriver/rlp-sms#1]
Ich würde mir wünschen, um meine Eingabe nicht zu wiederholen, dass es eine Sicherheitsabfrage gibt, wenn ich auf den Zurücksetzen Button tappe. "Bist du dir Sicher, deine Eingaben gehen dadurch verloren?"

**Comment by sancardriver** [comment]
Hinzugefügt
