### ISSUE TITLE
Plausibilitätsprüfung

### ISSUE THREAD

**Issue by JonasDeichelmann** [sancardriver/rlp-sms#2]
Eine Plausibilitätsprüfung würde insbesondere bei Alter, Gewicht, Ankunftszeit sinnvoll erscheinen.

Vorschlag für Plausibilitätsgrenzen:

Alter: 0-120 Jahre?
Gewicht: 0-350 kg?
Ankunftszeit: Aktuell - (+ 3h)?

**Comment by sancardriver** [comment]
Ankunftszeit schreibe ich noch in ein seperates Ticket!
