### ISSUE TITLE
Hiding von optionalen Infos

### ISSUE THREAD

**Issue by JonasDeichelmann** [sancardriver/rlp-sms#3]
Optionale Informationen, wie beispielsweise Kg, könnten in der Ausgabe rausgefiltert werden. Dadurch würden ausschließlich selbst angegebene Infos übermittelt werden.

**Comment by sancardriver** [comment]
Bin ich voll bei dir und kann ich auch gut verstehen. Leider ist das aber genau so durch den ÄLRD gewünscht. Das kam gerade aus den letzten Aktualisierungen nochmal hervor
